# Generated by Django 4.1.6 on 2023-02-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='', verbose_name='coach/%y/%m/%d')),
            ],
        ),
    ]
