# Generated by Django 4.1.6 on 2023-02-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('3 Month', '3 Month Subscription'), ('6 Month', '6 Month Subscription'), ('Year', 'Year Subscription'), ('Yoga', 'Yoga Sessions'), ('Boxing', 'Kick Boxing Sessions')], default='String', max_length=10)),
                ('price', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='offers/%y/%m/%d')),
            ],
        ),
    ]
